### ISSUE TITLE
Combination of MVC+Middleware+Wildcard Route give the error

### ISSUE THREAD

**Issue by popovserhii** [zendframework/zend-router#46]
I was inspired by Middleware and try it using with Zend MVC as described [here](http://zendframework.github.io/zend-mvc/middleware/). 
All worked well until I tried using Wildcard route.
When a route has 'middleware' config key with an array of Middleware applied it arise error  `rawurlencode() expects parameter 1 to be string, array given` in [`Wildcard::assemble()`](https://github.com/zendframework/zend-router/blob/master/src/Http/Wildcard.php#L171).

Minimal `routes` configuration to get error
```php
return [
    'routes' => [
        'default' => [
            'type' => 'Segment',
            'options' => [
                'route' => '/[:controller[/[:action]]]',
                'constraints' => [
                    'controller' => '[a-zA-Z]?[a-zA-Z0-9_-]*',
                    'action' => '[a-zA-Z]?[a-zA-Z0-9_-]*',
                ],
                'defaults' => [
                    'middleware' => [Page\ConnectivePage::class, Page\RendererMiddleware::class],
                    'controller' => 'index',
                    'action' => 'index',
                ],
            ],
            'may_terminate' => true,
            'child_routes' => [
                'wildcard' => [
                    'type' => 'Wildcard',
                    'priority' => 10,
                    'options' => [],
                ],
            ],
        ],
    ],
];
```

![image](https://user-images.githubusercontent.com/1991183/41356590-e79069a2-6f2c-11e8-8bcf-4ef90bee7709.png)

**Comment by froschdesign** [comment]
@popovserhii 
Please keep in mind, the route type `Wildcard` is deprecated.

https://docs.zendframework.com/zend-router/routing/#zend92router92http92wildcard-deprecated

**Comment by popovserhii** [comment]
@froschdesign 
This means that bug won't be fixed?

**Comment by froschdesign** [comment]
That‘s not the question! You should not use this route type because of the potential security issue.

**Comment by popovserhii** [comment]
I don't mind that there is a potential security issue. Could you give a link where I can read about this problem in more detail?

**Comment by froschdesign** [comment]
At the moment I can found only that: https://github.com/zendframework/zf2-documentation/issues/1320
