### ISSUE TITLE
Advanced Routing

### ISSUE THREAD

**Issue by kevspadilla** [zendframework/zend-router#52]
- [x] I was not able to find an [open](https://github.com/zendframework/zend-router/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-router/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [ ] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

I want to achieve this routing.

I want to achieve this kind of routing:

ParentRouteController
GET domain.com/parent-route
GET domain.com/parent-route/:value
POST domain.com/parent-route
UPDATE domain.com/parent-route/:value

ChildRoute1Controller
GET domain.com/parent-route/:value/child-route-1
GET domain.com/parent-route/:value/child-route-1/:child1value
POST domain.com/parent-route/:value/child-route-1
UPDATE domain.com/parent-route/:value/child-route-1/:child1value

ChildRoute2Controller
GET domain.com/parent-route/:value/child-route-1/:child1value/child-route-2
GET domain.com/parent-route/:value/child-route-1/:child1value/child-route-2/:childRoute2Value
POST domain.com/parent-route/:value/child-route-1/:child1value/child-route-2
UPDATE domain.com/parent-route/:value/child-route-1/:child1value/child-route-2/:childRoute2Value

I'm using ZF 2.5.2, thanks!

**Comment by froschdesign** [comment]
For questions, please use one of the following locations, and not the issue tracker:

- [Chat](https://zendframework.slack.com) ([get an invitation](https://zendframework-slack.herokuapp.com))
- [Forum](https://discourse.zendframework.com)

**Comment by Ocramius** [comment]
Just cross-linking https://discourse.zendframework.com/t/advanced-routing/790/2
