### ISSUE TITLE
Mark Query and Wildcard routes as deprecated

### ISSUE THREAD

**Issue by marcosh** [zendframework/zend-router#6]
The [documentation](http://zendframework.github.io/zend-router/routing/#zend92mvc92router92http92wildcard-deprecated) clearly states that the Query and Wildcard routes are deprecated. Both classed should be annotated with the `@deprecated` tag

**Comment by webimpress** [comment]
`Query` was marked as deprecated:
https://github.com/zendframework/zend-router/blob/release-2.7.3/src/Http/Query.php#L20
and it's already removed in v3.

`Wildcard` is still in v3:
https://github.com/zendframework/zend-router/blob/master/src/Http/Wildcard.php#L18
and it's not marked as deprecated, probably it should, as documentation states.

@marcosh you can always prepare your PR to zend-router :)

**Comment by aight8** [comment]
I really miss something similar than a wildcard route. Every middleware based http framework supports wildcard routes. In a MVC you should have a way to catch "all other" routes instead of hook in the 404 not found part. Hostname route is a workaround but it not catches the root path / -> "/")
